# Generated by Django 3.1.1 on 2020-10-08 14:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bowring', '0003_event_framepin_framescore_gamescore_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescore',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bowring.event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='base_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='handicap',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bowring.result'),
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
