# Generated by Django 3.1.1 on 2020-10-17 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bowring', '0004_auto_20201008_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='framescore',
            name='frame_type',
        ),
        migrations.AddField(
            model_name='framepin',
            name='throw_count',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
