# Generated by Django 3.1.1 on 2020-10-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowring', '0005_auto_20201017_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framepin',
            name='pin1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='framepin',
            name='pin10',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='framepin',
            name='pin2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='framepin',
            name='pin3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='framepin',
            name='pin4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='framepin',
            name='pin5',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='framepin',
            name='pin6',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='framepin',
            name='pin7',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='framepin',
            name='pin8',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='framepin',
            name='pin9',
            field=models.IntegerField(),
        ),
    ]
