# Generated by Django 3.1.1 on 2020-10-17 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bowring', '0006_auto_20201017_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framepin',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bowring.result'),
        ),
        migrations.AlterField(
            model_name='framescore',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bowring.result'),
        ),
    ]
